### ISSUE TITLE
CI を立てる

### ISSUE THREAD

**Issue by nonanonno** [nonanonno/catalyst#6]

**Comment by nonanonno** [comment]
Rust 向けは https://github.com/dtolnay/rust-toolchain を使うのが良さそう。以下使用例

```yml
name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
```

godot に依存した空プロジェクトで、44sかかった。
