### ISSUE TITLE
ROS 2 を繋げる

### ISSUE THREAD

**Issue by nonanonno** [nonanonno/catalyst#9]

**Comment by nonanonno** [comment]
参考になりそうな記事

- [共有オブジェクトを作る話](https://qiita.com/comocc/items/22ddc0ceda6e07ac9794)
- [Godot で ROS2 をやるサンプル。godot4に対応している](https://github.com/flynneva/godot_ros)

**Comment by nonanonno** [comment]
# GDExtension vs Module

https://docs.godotengine.org/ja/4.x/tutorials/scripting/gdextension/what_is_gdextension.html

Godot で C++ を使うにあたり、選択肢としては GDExtension と C++ module が考えられる。ここでは上記のドキュメントを元に、どちらを使うべきか考察する。

## 雑翻訳

GDExtension は Godot 固有の技術で、共有ライブラリを使ってエンジンとやりとりをする。この場合、エンジンの再コンパイルは不要になる。

C++向けには C++ modules も使うことができる。両者ともサードパーティーのライブラリをGodotに組込むことができる。どちらを選択するかはニーズによって決めるべき。

> 警告: GDExtension のゴールは、マイナーバージョンの更新で壊れないことだが、まだ達成されていない。破壊的変更が入る可能性があることに注意。例えば、4.0向けの GDExtension は 4.1 では使用できない。4.2 向けの GDExtension は 4.3 で動くはず

### GDExtension の長所

- エンジンのソースコードを再コンパイルする必要はない
- GDScript と C# でアクセスできる API のほぼすべてにアクセスできる
- Add-on として作れる
- C と C++ 以外も対応することができる
- GDExtension では、 editor と エクスポートしたプロジェクトの両方で使うことができる。モジュールではエクスートテンプレートを再コンパイルする必要がある
- GDExtension ではライブラリをビルドするだけで良いが、モジュールではエンジン自体を再ビルドする必要がある。これは、開発速度を低迷させる

### C++ module の長所

- C++ module を使うのは、 GDEXtension では機能が足りないときにすべき
- エンジンとより深い結合を提供する
- ライブラリファイルを取り込むことなく、プロジェクトに追加の機能を提供することができる。(GDExtension では共有ライブラリが別途存在することになる？)

> 注釈: GDExtension でアクセスできない機能があったらissue 立ててくれ


## 方向性

基本的に GDExtension を使うのが良さそう。C++ module にすると、常にROS2を使う形になりそう。プラグイン的にしたい。

**Comment by nonanonno** [comment]
# ROS 2 with GDExtension

ROS 2 を GDExtension で組込む手順は以下の通り。ここでは ROS 2 環境内に Godot を入れる形を取る(overlay)。Godot 自体は単独バイナリなので、単にROS 2 環境にダウンロードしておくだけになる。

1. C++ 向けの GDExtension のボイラープレートを作成する
2. SConstruct に ROS 2 をリンクするための設定を追加する
3. ROS 2 ノードを作成する
4. Godot で利用する


## 1. C++ 向け GDExtension

https://docs.godotengine.org/ja/4.x/tutorials/scripting/gdextension/gdextension_cpp_example.html

↑ を参考に構築していく。チュートリアルをやっておくと良いが、最低限 `register_types.*` があれば空でも良い。ここでは `rosbridge` という名前で作成する。(intellisense の都合で .h ではなく .hpp にしている)


```
rosbridge
├── godot-cpp
├── SConstruct
└── src
    ├── register_types.cpp
    └── register_types.hpp
```

<details><summary>SConstruct</summary>

```python
#!/usr/bin/env python
import os

NAME = "rosbridge"
DEST = "bin"

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags


# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")


if env["platform"] == "macos":
    library = env.SharedLibrary(
        f"{DEST}/lib{NAME}.{env['platform']}.{env['target']}.framework/lib{NAME}.{env['platform']}.{env['target']}",
        source=sources,
    )
else:
    library = env.SharedLibrary(
        f"{DEST}/lib{NAME}{env['suffix']}{env['SHLIBSUFFIX']}",
        source=sources,
    )

Default(library)
```
</details>

<details><summary>register_types.hpp</summary>

```c++
#pragma once

#include <godot_cpp/core/class_db.hpp>

using namespace godot;

void initialize_rosbridge_module(ModuleInitializationLevel p_level);
void uninitialize_rosbridge_module(ModuleInitializationLevel p_level);
```
</details>

<details><summary>register_types.cpp</summary>

```c++
#include "register_types.hpp"

#include <gdextension_interface.h>
#include <godot_cpp/core/defs.hpp>
#include <godot_cpp/godot.hpp>

using namespace godot;

void initialize_rosbridge_module(ModuleInitializationLevel p_level) {
  if (p_level != godot::MODULE_INITIALIZATION_LEVEL_SCENE) {
    return;
  }

  // ここに追加していく
}

void uninitialize_rosbridge_module(ModuleInitializationLevel p_level) {
  if (p_level != godot::MODULE_INITIALIZATION_LEVEL_SCENE) {
    return;
  }
}

extern "C" {
GDExtensionBool GDE_EXPORT
rosbridge_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address,
                       const GDExtensionClassLibraryPtr p_library,
                       GDExtensionInitialization *r_initialization) {
  godot::GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library,
                                                 r_initialization);
  init_obj.register_initializer((initialize_rosbridge_module));
  init_obj.register_terminator(uninitialize_rosbridge_module);
  init_obj.set_minimum_library_initialization_level(
      godot::MODULE_INITIALIZATION_LEVEL_SCENE);

  return init_obj.init();
}
}
```
</details>

この状態でビルドできることを確認する。(試してないがもしかしたら1つぐらいクラスの追加が必要かも)

```shell
# まずは godot-cpp のセットアップ
git submodule add -b 4.2 https://github.com/godotengine/godot-cpp

cd godot-cpp
git submodule update --init

pushd /tmp
godot --dump-extension-api --headless
popd

scons platform=linux custom_api_file=/tmp/extension_api.json

# rosbridge に戻る
cd ..

scons platform=linux
```

次に、Godot プロジェクト内に gdextension ファイルを用意する。ここでは Godot プロジェクトルートに設置する。

<details><summary>rosbridge.gdextension</summary>

```toml
entry_symbol = "rosbridge_library_init"
compatibility_minimum = "4.2"

[libraries]
macos.debug = "res://../rosbridge/bin/librosbridge.macos.template_debug.framework"
macos.release = "res://../rosbridge/bin/librosbridge.macos.template_release.framework"
linux.debug.x86_64 = "res://../rosbridge/bin/librosbridge.linux.template_debug.x86_64.so"
linux.release.x86_64 = "res://../rosbridge/bin/librosbridge.linux.template_release.x86_64.so"
windows.debug.x86_64 = "res://../rosbridge/bin/librosbridge.windows.template_debug.x86_64.dll"
windows.release.x86_64 = "res://../rosbridge/bin/librosbridge.windows.template_release.x86_64.dll"
```

</details>

## 2. SConstruct に ROS 2 をリンクするための設定を追加する

https://github.com/flynneva/godot_ros を参考にしている。

内容としては、include ディレクトリと lib ディレクトリを見えるようにする。 ROS 2 humble から include ディレクトリの構造が変わっているので注意が必要。ここでは humble 以上のみに対応する形にする。

scons ファイルは python なので、python でヘルパー関数を書きつつ進める。

```python
# ファイル先頭あたりに定数を追加
ROS_DISTRO = os.environ.get("ROS_DISTRO")
ROS_DIR = f"/opt/ros/{ROS_DISTRO}"

...

# include と lib を抽出するヘルパー関数を追加
def getSubDirs(base_path: str):
    return [
        path
        for name in os.listdir(base_path)
        if os.path.isdir(path := os.path.join(base_path, name))
    ]


def getLibNames(base_path: str):
    return [
        name
        for name in os.listdir(base_path)
        if os.path.isfile(os.path.join(base_path, name))
        if name.endswith(".so") or name.endswith(".a")
    ]

...
# ROS 2 設定を追加
env.Append(CPPPATH=getSubDirs(f"{ROS_DIR}/include"))
env.Append(CCFLAGS=["-fexceptions"])
env.Append(LIBPATH=[f"{ROS_DIR}/lib"])
env.Append(LIBS=getLibNames(f"{ROS_DIR}/lib"))

...

```

godot-cpp では デフォルトでは例外を無効にしている。バイナリサイズの削減とコンパイル時間の削減のためらしい。

>    Disable exception handling. Godot doesn't use exceptions anywhere, and this
>    saves around 20% of binary size and very significant build time.

しかし、ROS 2 では例外を使っているので `-fexceptions` の設定を改めて追加するか `disable_exceptions=no` でビルドするかが必要。ここでは前者を使用している。(違いがあるのかよくわかっていない)


## 3. ROS 2 ノードを作成する

(以降では ROS 2 の「ノード」と Godot の「ノード」が混在することに注意)

talker ROS 2 ノードを追加してみる。Godot ノード として作るのではなく、RefCounted を継承する、GDScript から利用されるパーツとして作る。GDExtension C++ のチュートリアルでは Sprite2d を継承したものを作っているので参考にする。

<details><summary>talker.hpp</summary>

```c++
#pragma once

#include <godot_cpp/classes/ref_counted.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/string.hpp>

namespace godot {
class Talker : public RefCounted {
  GDCLASS(Talker, RefCounted)

public:
  Talker();
  ~Talker();
  void spin_some();
  void talk(const int &count);

protected:
  static void _bind_methods();

  std::shared_ptr<rclcpp::Node> node_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_;
};
} // namespace godot
```

</details>


<details><summary>talker.cpp</summary>

```c++
#include "talker.hpp"
#include <godot_cpp/core/class_db.hpp>
#include <string>

using namespace godot;

Talker::Talker() {
  rclcpp::init(0, nullptr);

  node_ = std::make_shared<rclcpp::Node>("godot_talker_node");
  pub_ = node_->create_publisher<std_msgs::msg::String>("talker", 10);
}

Talker::~Talker() { rclcpp::shutdown(); }

void Talker::spin_some() { rclcpp::spin_some(node_); }

void Talker::talk(const int &count) {
  std_msgs::msg::String msg;
  msg.data = "Hello from godot: " + std::to_string(count);
  RCLCPP_INFO(node_->get_logger(), "Publishing: '%s'", msg.data.c_str());
  pub_->publish(msg);
}

void Talker::_bind_methods() {
  ClassDB::bind_method(D_METHOD("talk", "count"), &Talker::talk);
  ClassDB::bind_method(D_METHOD("spin_some"), &Talker::spin_some);
}
```

</details>

ややこしい形になっているが、`Talker` クラスは Godot の要素として作っている。 ROS 2 ノードは `rclcpp::Node` を継承したクラスを作るのではなく、手続的に構築している。実際やる時は ROS 2 ノードとしてのクラスを作って、 Godot 側のクラスがそれを使用する形になりそう。

上記を作った上で、 `register_types.cpp` に以下の行を追加する。

```c++
#include "talker.hpp"
...


void initialize_rosbridge_module(ModuleInitializationLevel p_level) {
  ...

  ClassDB::register_class<Talker>();
}
```
ビルドしておく。

```shell
scons platform=linux
```


## 4. Godot で利用する

上記まで完了したら、Godot から読み込めるようになるはず。何か上手くいかなかったら Godot を再起動する。

なお、ROS 2 は共有ライブラリとしてリンクしているため、`source /opt/ros/$ROS_DISTRO/setup.bash` をした状態で godot を起動する必要がある。

GDScript を1つ用意して、以下のように記述する。

```gdscript
extends Node3D

var node = Talker.new()

var count = 1
var g_timer = null

# Called when the node enters the scene tree for the first time.
func _ready():
    node.spin_some()
    g_timer = Timer.new()
    add_child(g_timer)

    g_timer.connect("timeout", _on_Timer_timeout)
    g_timer.wait_time = 1.0
    g_timer.one_shot = false
    g_timer.start()

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
    pass

func _on_Timer_timeout():
    print("godot is talking: ", count)
    # talk callback publishes to ROS
    node.talk(count)
    count += 1
```

これを適当なノードにアタッチして実行して、`ros2 node list` と `ros2 topic echo /chatter` で見れることを確認する。

**Comment by nonanonno** [comment]
# scons その他

- clang を使う場合は `use_llvm=yes` を追加する
- release ビルドを行う場合は `target=template_release` を追加する
- compile_commands.json を追加する場合は、以下の記述を追加した上で、`compiledb=yes`  を追加する

```python
# compile_commands
env["COMPILATIONDB_USE_ABSPATH"] = True
env.Tool("compilation_db")
env.CompilationDatabase()
```

**Comment by nonanonno** [comment]
# CI 向け

GDExtension for C++ のビルド手順を愚直にやるとそこそこコンパイルに時間がかかる。これはCIでは致命的なので対策が必要。

scons にはキャッシュディレクトリを使う機能がある。ドキュメントは[このあたり](https://scons.org/doc/2.0.0.final.0/HTML/scons-user/c4213.html) でこれは SConstruct に直接設定を記述する方法。どこにドキュメントが書いてあるかわからないが、環境変数 `SCONS_CACHE` を設定することでそこにキャッシュを置けるらしい。


- https://github.com/godotengine/godot/blob/master/.github/actions/godot-build/action.yml
- https://github.com/godotengine/godot/blob/master/.github/actions/godot-cache/action.yml

これと actions/cache を組み合わせてキャッシュができるはず。動かしていないが、以下のようなワークフローになるはず。(プロジェクトルートが GDExtension として)

```yaml
...
env:
  SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
  SCONS_CACHE_LIMIT: "7168"

jobs:
  build:
    name: Build with scons
    matrix:
      godot_version: 4.2.2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.SCONS_CACHE }}
          key: name-${{ matrix.godot_version }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            name-${{ matrix.godot_version }}-${{ github.ref }}-${{ github.sha }}
            name-${{ matrix.godot_version }}-${{ github.ref }}
            name-${{ matrix.godot_version }}
      - run: |
          godot --dump-extension-api --headless
          pushd godot-cpp
          scons platform=linux custom_api=../extension_api.json
          popd
          scons platform=linux
```


これにより、(ほぼ中身がない) rosbridge のビルドが 27分 → 28s になった。(コード変更なしで)
